#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx commitlint --edit "$1" || {
  echo "\033[0;31mYour commit message is invalid! Follow this format:\033[0m"
  echo ""
  echo "  type(scope?): subject"
  echo ""
  echo "Examples:"
  echo "  feat: Add a new user login page"
  echo "  fix(auth): Resolve login failure issue"
  exit 1
}
